seed_everything: 7
trainer:
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 10
        monitor: val_ExpRate
        mode: max
        filename: '{epoch}-{step}-{val_ExpRate:.4f}'
  gpus: [0]
  accelerator: ddp
  max_epochs: 120
  deterministic: true
  check_val_every_n_epoch: 1
  resume_from_checkpoint: /workspace/codes/ICAL_image/lightning_logs/version_150/checkpoints/epoch=21-step=223277-val_ExpRate=0.7630.ckpt

model:
  d_model: 256
  # encoder
  growth_rate: 24
  num_layers: 16
  # decoder
  nhead: 8
  num_decoder_layers: 3
  dim_feedforward: 1024
  dc: 32
  dropout: 0.3
  vocab_size: 250  # 245 + 4 + # /workspace/codes/ICAL/ical/datamodule/vocab.py, lines 13--16
  cross_coverage: true
  self_coverage: true
  # beam search
  beam_size: 10
  max_len: 72
  alpha: 1.0
  early_stopping: false
  temperature: 1.0
  # training
  learning_rate: 0.01
  patience: 4
  dynamic_weight: false

data:
  folder: /workspace/HME100k_rsx
  test_folder: test
  max_size: 540000
  scale_to_limit: false
  train_batch_size: 8
  eval_batch_size: 2
  num_workers: 2
  scale_aug: false
